# Generated by Django 3.0.5 on 2020-04-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=100)),
                ('No_of_Copies', models.PositiveIntegerField(default=0)),
                ('Publisher_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Publish_Date', models.DateField(blank=True, null=True)),
                ('Create_On', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
